networks:
  backend:
    driver: bridge
  kafka-net:
    driver: bridge


version: '3'
services:

  consul:
    image: "consul:1.15.4"
    hostname: "im-consul"
    command: "agent -dev -client 0.0.0.0 -ui"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    networks:
      - kafka-net
      - backend

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: im-zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  
  kafka:
    image: wurstmeister/kafka
    container_name: im-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    networks:
      - kafka-net
      - backend
      
  mysql:
    build:
      context: mysql
    container_name: im-mysql
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${MYSQL_USERNAME}                  # 设置 MySQL 用户名称
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}              # 设置 MySQL 用户密码
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    # 设置 MySQL root 用户密码
      - MYSQL_DATABASE=${MYSQL_DATABASE}              # 设置 MySQL 初始化数据库
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql        # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 MySQL 数据的目录挂载到容器中 /var/lib/mysql 目录
    ports:
      - "${MYSQL_PORT}:3306"                          # 设置容器3306端口映射指定宿主机端口
    networks:
      - backend
      - kafka-net
    restart: always
  
  redis:
    build:
      context: redis
    container_name: im-redis
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
     - ${CODE_PATH_HOST}/redis:/data:rw                 # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Redis 数据的目录挂载到容器中 /data 目录
    ports:
      - "${REDIS_PORT}:6379"                          # 设置容器6379端口映射指定宿主机端口
    networks:
      - backend
      - kafka-net
    restart: always