// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.18.0
// source: api/protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation_Type int32

const (
	// Handshake 握手
	Operation_Handshake Operation_Type = 0
	// HandshakeResp 握手应答
	Operation_HandshakeResp Operation_Type = 1
	// Heartbeat 心跳
	Operation_Heartbeat Operation_Type = 2
	// HeartbeatResp 心跳回复
	Operation_HeartbeatResp Operation_Type = 3
	// SendMsg 发送消息
	Operation_SendMsg Operation_Type = 4
	// SendMsgResp 发送消息回复
	Operation_SendMsgResp Operation_Type = 5
	// DisconnectResp 断开连接回复
	Operation_DisconnectResp Operation_Type = 6
	// Auth 授权连接
	Operation_Auth Operation_Type = 7
	// AuthResp 授权连接回复
	Operation_AuthResp Operation_Type = 8
	// Raw 原始消息
	Operation_Raw Operation_Type = 9
	// ProtoReady 协议准备就绪
	Operation_ProtoReady Operation_Type = 10
	// ProtoFinish 协议完成
	Operation_ProtoFinish Operation_Type = 11
	// ChangeRoom 更换房间
	Operation_ChangeRoom Operation_Type = 12
	// ChangeRoomResp 更换房间回复
	Operation_ChangeRoomResp Operation_Type = 13
	// Sub 订阅
	Operation_Sub Operation_Type = 14
	// SubReply 订阅操作回复
	Operation_SubReply Operation_Type = 15
	// Unsub 取消订阅操作
	Operation_Unsub Operation_Type = 16
	// UnsubReply 取消订阅操作回复
	Operation_UnsubResp Operation_Type = 17
)

// Enum value maps for Operation_Type.
var (
	Operation_Type_name = map[int32]string{
		0:  "Handshake",
		1:  "HandshakeResp",
		2:  "Heartbeat",
		3:  "HeartbeatResp",
		4:  "SendMsg",
		5:  "SendMsgResp",
		6:  "DisconnectResp",
		7:  "Auth",
		8:  "AuthResp",
		9:  "Raw",
		10: "ProtoReady",
		11: "ProtoFinish",
		12: "ChangeRoom",
		13: "ChangeRoomResp",
		14: "Sub",
		15: "SubReply",
		16: "Unsub",
		17: "UnsubResp",
	}
	Operation_Type_value = map[string]int32{
		"Handshake":      0,
		"HandshakeResp":  1,
		"Heartbeat":      2,
		"HeartbeatResp":  3,
		"SendMsg":        4,
		"SendMsgResp":    5,
		"DisconnectResp": 6,
		"Auth":           7,
		"AuthResp":       8,
		"Raw":            9,
		"ProtoReady":     10,
		"ProtoFinish":    11,
		"ChangeRoom":     12,
		"ChangeRoomResp": 13,
		"Sub":            14,
		"SubReply":       15,
		"Unsub":          16,
		"UnsubResp":      17,
	}
)

func (x Operation_Type) Enum() *Operation_Type {
	p := new(Operation_Type)
	*p = x
	return p
}

func (x Operation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protocol_protocol_proto_enumTypes[0].Descriptor()
}

func (Operation_Type) Type() protoreflect.EnumType {
	return &file_api_protocol_protocol_proto_enumTypes[0]
}

func (x Operation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation_Type.Descriptor instead.
func (Operation_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_protocol_protocol_proto_rawDescGZIP(), []int{1, 0}
}

type Proto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver  int32  `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Op   int32  `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Seq  int32  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Body []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Proto) Reset() {
	*x = Proto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protocol_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto) ProtoMessage() {}

func (x *Proto) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto.ProtoReflect.Descriptor instead.
func (*Proto) Descriptor() ([]byte, []int) {
	return file_api_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Proto) GetVer() int32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *Proto) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *Proto) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Proto) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protocol_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_api_protocol_protocol_proto_rawDescGZIP(), []int{1}
}

var File_api_protocol_protocol_proto protoreflect.FileDescriptor

var file_api_protocol_protocol_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x4f, 0x0a, 0x05, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x76, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xa1, 0x02, 0x0a, 0x09,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x93, 0x02, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73,
	0x67, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68,
	0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x10, 0x08,
	0x12, 0x07, 0x0a, 0x03, 0x52, 0x61, 0x77, 0x10, 0x09, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x10, 0x0b, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x0c, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x10, 0x0d, 0x12, 0x07,
	0x0a, 0x03, 0x53, 0x75, 0x62, 0x10, 0x0e, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x10, 0x0f, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x10, 0x10,
	0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x52, 0x65, 0x73, 0x70, 0x10, 0x11, 0x42,
	0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_protocol_protocol_proto_rawDescOnce sync.Once
	file_api_protocol_protocol_proto_rawDescData = file_api_protocol_protocol_proto_rawDesc
)

func file_api_protocol_protocol_proto_rawDescGZIP() []byte {
	file_api_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_api_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protocol_protocol_proto_rawDescData)
	})
	return file_api_protocol_protocol_proto_rawDescData
}

var file_api_protocol_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_protocol_protocol_proto_goTypes = []interface{}{
	(Operation_Type)(0), // 0: im.protocol.Operation.Type
	(*Proto)(nil),       // 1: im.protocol.Proto
	(*Operation)(nil),   // 2: im.protocol.Operation
}
var file_api_protocol_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protocol_protocol_proto_init() }
func file_api_protocol_protocol_proto_init() {
	if File_api_protocol_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protocol_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protocol_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protocol_protocol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_api_protocol_protocol_proto_depIdxs,
		EnumInfos:         file_api_protocol_protocol_proto_enumTypes,
		MessageInfos:      file_api_protocol_protocol_proto_msgTypes,
	}.Build()
	File_api_protocol_protocol_proto = out.File
	file_api_protocol_protocol_proto_rawDesc = nil
	file_api_protocol_protocol_proto_goTypes = nil
	file_api_protocol_protocol_proto_depIdxs = nil
}
